import esbuild from 'esbuild';
import process from 'process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const jspdfEsPath = fileURLToPath(new URL('./node_modules/jspdf/dist/jspdf.es.js', import.meta.url));

// jsPDF bundelt drei nie von uns aufgerufene `output(...)`-Varianten
// (`pdfobjectnewwindow`/`pdfjsnewwindow`/`dataurlnewwindow`), die ein neues
// Fenster oeffnen und dort per `createElement('script'/'iframe')` +
// `appendChild` Inhalte injizieren (u.a. ein externes CDN-Script). Wir rufen
// nur `output('arraybuffer')` auf (siehe export/pdf-export.ts) — der Code ist
// totes Gewicht, aber esbuild kann ihn nicht wegtreeshaken (dynamischer
// String-`switch`), und der Obsidian-Store-Review flaggt dynamische
// Script-Element-Erstellung im Bundle als Error, unabhaengig davon ob der
// Pfad je erreicht wird. Fix: vor dem Bundling die drei toten Cases aus dem
// unminifizierten ESM-Quellfile herausschneiden (`alias` erzwingt genau
// diese Datei statt der von esbuilds Default-Resolution gewaehlten
// `.min.js`) — bricht hart, falls ein jsPDF-Update das Pattern aendert,
// damit das nie unbemerkt wieder reinrutscht.
const stripDeadWindowCasesPlugin = {
	name: 'strip-jspdf-dead-window-cases',
	setup(build) {
		build.onLoad({ filter: /jspdf\.es\.js$/ }, ({ path }) => {
			const original = readFileSync(path, 'utf8');
			const patched = original.replace(/case "pdfobjectnewwindow":[\s\S]*?(?=case "datauri":)/, '');
			if (patched === original) {
				throw new Error(
					`strip-jspdf-dead-window-cases: Pattern nicht gefunden in ${path} — jsPDF-Update? Pattern in esbuild.config.mjs nachziehen, sonst landet die entfernte Script-Injection ungeprueft wieder im Bundle.`,
				);
			}
			return { contents: patched, loader: 'js' };
		});
	},
};

// jspdf-autotable/xlsx werden NICHT in `external` gelistet -> esbuild
// bundlet sie voll in main.js. Beide sind reines JS (keine Node-only APIs),
// laufen daher unveraendert auch auf iOS/Android (siehe manifest.json
// isDesktopOnly:false). jspdf selbst ebenfalls gebundelt, aber ueber den
// Alias oben auf die gepatchte Quelldatei umgeleitet.
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	alias: {
		jspdf: jspdfEsPath,
	},
	plugins: [stripDeadWindowCasesPlugin],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
