import esbuild from 'esbuild';
import process from 'process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const jspdfEsPath = fileURLToPath(new URL('./node_modules/jspdf/dist/jspdf.es.js', import.meta.url));

// jsPDF ships three `output(...)` variants we never call
// (`pdfobjectnewwindow`/`pdfjsnewwindow`/`dataurlnewwindow`) that open a
// window and inject a <script>/<iframe> (incl. an external CDN script).
// esbuild cannot tree-shake them (dynamic string switch) and the Obsidian
// plugin review flags runtime script creation regardless of reachability.
// So the dead cases are cut out of the unminified ESM source before bundling
// (`alias` forces that file). Throws if a jsPDF update changes the pattern,
// so the injection never sneaks back in unnoticed.
const stripDeadWindowCasesPlugin = {
	name: 'strip-jspdf-dead-window-cases',
	setup(build) {
		build.onLoad({ filter: /jspdf\.es\.js$/ }, ({ path }) => {
			const original = readFileSync(path, 'utf8');
			const patched = original.replace(/case "pdfobjectnewwindow":[\s\S]*?(?=case "datauri":)/, '');
			if (patched === original) {
				throw new Error(
					`strip-jspdf-dead-window-cases: pattern not found in ${path} — jsPDF update? Adjust the pattern in esbuild.config.mjs, otherwise the script injection ends up in the bundle again.`,
				);
			}
			return { contents: patched, loader: 'js' };
		});
	},
};

// jspdf, jspdf-autotable and xlsx are bundled (pure JS, runs on iOS/Android
// as well); jspdf via the alias above so the patched source is used.
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	alias: {
		jspdf: jspdfEsPath,
	},
	plugins: [stripDeadWindowCasesPlugin],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
